#ifndef MINI_I2C_HWMON_H
#define MINI_I2C_HWMON_H

enum mini_i2c_fault {
    MINI_I2C_FAULT_NONE = 0,
    MINI_I2C_FAULT_READ_TIMEOUT,
    MINI_I2C_FAULT_DEVICE_DISAPPEARED,
    MINI_I2C_FAULT_STUCK_VALUE,
    MINI_I2C_FAULT_OUT_OF_RANGE,
    MINI_I2C_FAULT_INVALID_READING,
};

#endif
